INSERT INTO users (username, password, email) VALUES ('alyssa', 1234, 'agraham@email.com');
INSERT INTO users (username, password, email) VALUES ('ben', 1234, 'benc@email.com');
INSERT INTO users (username, password, email) VALUES ('mace', 1234, 'mace@email.com');
INSERT INTO users (username, password, email) VALUES ('jim', 1234, 'jim@email.com');
INSERT INTO users (username, password, email) VALUES ('marie', 1234, 'jim@email.com');
INSERT INTO users (username, password, email) VALUES ('zoe', 1234, 'jim@email.com');
INSERT INTO users (username, password, email) VALUES ('noemi', 1234, 'jim@email.com');
INSERT INTO rides (name, pickup, destination, pickup_date, pickup_time, driver_user_id, passenger_slots) VALUES ('going to solider field', 'some place', 'solider field', '2018-05-11', '09:30:00', 1, 3);
INSERT INTO rides (name, pickup, destination, pickup_date, pickup_time, driver_user_id, passenger_slots) VALUES ('going to united center', 'some where', 'united center', '2018-05-15', '10:00:00', 1, 2);
INSERT INTO rides (name, pickup, destination, pickup_date, pickup_time, driver_user_id, passenger_slots) VALUES ('going to see da bears', 'some place there', 'solider field', '2018-05-19', '13:30:00', 1, 4);
INSERT INTO rides (name, pickup, destination, pickup_date, pickup_time, driver_user_id, passenger_slots) VALUES ('going to mccormick place', 'some here', 'mccormick place', '2018-05-11', '19:00:00', 2, 4);
INSERT INTO rides (name, pickup, destination, pickup_date, pickup_time, driver_user_id, passenger_slots) VALUES ('navy pier rulez', 'some place', 'navy pier', '2018-05-13', '07:30:00', 2, 1);
INSERT INTO rides (name, pickup, destination, pickup_date, pickup_time, driver_user_id, passenger_slots) VALUES ('daaaa bears', 'some place near', 'solider field', '2018-05-18', '08:00:00', 2, 2);
INSERT INTO rides (name, pickup, destination, pickup_date, pickup_time, driver_user_id, passenger_slots) VALUES ('dat pier', 'some place far', 'navy pier', '2018-05-21', '22:30:00', 3, 4);
INSERT INTO rides (name, pickup, destination, pickup_date, pickup_time, driver_user_id, passenger_slots) VALUES ('going to solider field', 'some place', 'solider field', '2018-05-16', '18:00:00', 3, 3);
INSERT INTO rides (name, pickup, destination, pickup_date, pickup_time, driver_user_id, passenger_slots) VALUES ('go cubs gooooo', 'somewhere here', 'wrigley field', '2018-05-18', '22:30:00', 4, 4);
INSERT INTO rides (name, pickup, destination, pickup_date, pickup_time, driver_user_id, passenger_slots) VALUES ('outdoor concert', 'somewhere there', 'soldier field', '2018-05-18', '24:30:00', 4, 3);
INSERT INTO rides (name, pickup, destination, pickup_date, pickup_time, driver_user_id, passenger_slots) VALUES ('hockeyyyy', 'some place', 'united center', '2018-05-18', '02:00:00', 4, 2);
INSERT INTO rides (name, pickup, destination, pickup_date, pickup_time, driver_user_id, passenger_slots) VALUES ('conferences', 'some place far', 'mccormick place', '2018-05-18', '09:30:00', 4, 1);
INSERT INTO rides_users (user_id, ride_id) VALUES (7, 12);
INSERT INTO rides_users (user_id, ride_id) VALUES (6, 5);
INSERT INTO rides_users (user_id, ride_id) VALUES (5, 1);
INSERT INTO rides_users (user_id, ride_id) VALUES (4, 2);
INSERT INTO rides_users (user_id, ride_id) VALUES (1, 4);
INSERT INTO rides_users (user_id, ride_id) VALUES (2, 3);
INSERT INTO rides_users (user_id, ride_id) VALUES (3, 11);
INSERT INTO rides_users (user_id, ride_id) VALUES (4, 10);
INSERT INTO rides_users (user_id, ride_id) VALUES (6, 9);
INSERT INTO rides_users (user_id, ride_id) VALUES (5, 8);
INSERT INTO rides_users (user_id, ride_id) VALUES (6, 3);
INSERT INTO rides_users (user_id, ride_id) VALUES (3, 4);
INSERT INTO rides_users (user_id, ride_id) VALUES (2, 5);
INSERT INTO rides_users (user_id, ride_id) VALUES (1, 2);
INSERT INTO rides_users (user_id, ride_id) VALUES (2, 1);